version: 1.0.0.{build}

configuration:
 - Release

platform:
 - Win32
 - x64

image:
 - Visual Studio 2019

build:
 project: vs2010.sln
 verbosity: minimal
 parallel: true

build_script:
 - ps: devenv /upgrade vs2010.vcxproj
 - ps: msbuild vs2010.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
