version: 1.1.0.{build}

configuration:
 - Release

platform:
 - Win32
 - x64

image:
 - Visual Studio 2019

build:
 project: vs2010.sln
 verbosity: minimal
 parallel: true

before_build :
 - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /upgrade vs2010.sln'
 - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /upgrade vs2010.vcxproj'